### ISSUE TITLE
Testing in a local network

### ISSUE THREAD

**Issue by MalteBartels** [dhbw-timetable/rablabla#102]
Currently, testing is only possible on the localhost, due to this line in Main.js:

`const ajaxTarget = window.location.href.indexOf('localhost') !== -1 ? 'https://rablabla-staging.mybluemix.net' : '';`

You could override that, for example to test on an iPhone in your local network. However, then you run into a CORS-error.
Is it possible, to solve this some how?

**Comment by hendriku** [comment]
@MalteBartels I'll fix CORS Header in our staging backend soon. Therefore I'll be allowing external requests to it and force all URLs which do not match rablabla or rablabla-staging subdomain to use the staging backend. This will make it easier for you to test.
