### ISSUE TITLE
Website https://rablabla.hobbytes.de/ is not working anymore

### ISSUE THREAD

**Issue by lage2104** [dhbw-timetable/rablabla#129]
Tested with different keys and url from dhbw stuttgart.
No lecture are displaying.

**Comment by hendriku** [comment]
Sorry for the inconvenience. I can reproduce the issue and will see what I can do.

**Comment by hendriku** [comment]
@lage2104 okay so a kernel hotpatch in the infrastructure went wrong. I did reset it and it appears to work again. Feel free to reopen the issue if the problem persists.
