### ISSUE TITLE
Day Title not vertically centered

### ISSUE THREAD

**Issue by hendriku** [dhbw-timetable/rablabla#18]
<img width="111" alt="bildschirmfoto 2017-10-25 um 15 49 54" src="https://user-images.githubusercontent.com/8998518/32002285-6bf51c20-b99c-11e7-9a22-45b69ae00532.png">
I think there should be not that much space above the heading. Maybe reduce top and for more overview.

**Comment by hendriku** [comment]
<img width="406" alt="bildschirmfoto 2017-10-25 um 15 53 05" src="https://user-images.githubusercontent.com/8998518/32002359-9f76b838-b99c-11e7-884f-6eccb7a2b74e.png"> This may be because of the NavigationBar component. It is not barely our fault but we should fix this till production.

**Comment by MalteBartels** [comment]
Technically, it is aligned correctly. But: you can't see it, as the body is also grey. I'll keep this in mind

**Comment by MalteBartels** [comment]
@hendriku Is it fixed now?

**Comment by hendriku** [comment]
@MalteBartels Yes! Thanks
