### ISSUE TITLE
Padding on events

### ISSUE THREAD

**Issue by hendriku** [dhbw-timetable/rablabla#30]
We should have a little bit more padding in the events especially und the right side. @MalteBartels  Can you approve this?

**Comment by hendriku** [comment]
![image](https://user-images.githubusercontent.com/8998518/32143767-e0471690-bcae-11e7-8ac7-ff5c1dbbcad2.png)

**Comment by MalteBartels** [comment]
jep totally

**Comment by MalteBartels** [comment]
More padding everywhere;)
