### ISSUE TITLE
Questionable width sizing of chat messages

### ISSUE THREAD

**Issue by hendriku** [dhbw-timetable/rablabla#31]
We should have a chat interface for our ChatBot. If one of us two has time for this, this is a reminder to do it.

**Comment by hendriku** [comment]
@MalteBartels How can we optimize the current implementation for mobile devices?

**Comment by hendriku** [comment]
I implemented viewport width with my latest push. I think we should also provide a fallback for browsers which not support vw.

**Comment by MalteBartels** [comment]
How about making the modal fullscreen on small devices? 
`vw` and `vh` are well support across all browsers, according to [canIUse](http://caniuse.com/#search=vw). Even quite old versions of IE

**Comment by hendriku** [comment]
I agree that there should be a fullscreen modal on small devices but the popover for medium and above. Lets keep this in mind for after release.

**Comment by hendriku** [comment]
<img width="450" alt="bildschirmfoto 2017-11-04 um 17 00 57" src="https://user-images.githubusercontent.com/8998518/32406984-e18c39fe-c181-11e7-9dc0-ef287bdebdd7.png">
@MalteBartels Can we achieve that the messages are better formatted (content based auto width)?

**Comment by hendriku** [comment]
@MalteBartels I think this is not relevant for release v1.0 but still active.
