### ISSUE TITLE
v1.1 caches

### ISSUE THREAD

**Issue by hendriku** [dhbw-timetable/rablabla#32]
As it is **not possible** that our site will load the appointments faster than rapla does, we have to cache the information like: dailyEvents, url to simulate fast loading.

**Comment by hendriku** [comment]
@MalteBartels This has now higher priority since we now have the onboarding modal. We have to store key and title so that users don't have enter it every pageload.

**Comment by MalteBartels** [comment]
Caching the key and the course should work now. The rest is sugar;)

**Comment by MalteBartels** [comment]
Last loaded events are cached now... We should cache into the future, as well as display error messages. Currently switching the date in offline mode has no effect at all

**Comment by hendriku** [comment]
Current topics to take care of are:
- [X] AppCache API is deprecated. Let us try to find a nice modern solution. (for now okay)
- [X] Cache must be updated correctly. See #76  
- [ ] Cache has to be expanded to at least 3 weeks (before, current and next) and has to be kept clean (delete old weeks). See #75 

Update: 
1. I could achieve to update cache properly via specifying a `no-cache` filter for the `manifest.appcache` file. (See http://blog.jamesdbloom.com/ProblemsWithApplicationCache.html)
Now we can change date **and/or** version in our manifest and our app will properly update on all devices. 
2. As we discussed... ServiceWorkers are simply not ready yet! <img width="1264" alt="bildschirmfoto 2018-01-03 um 14 53 05" src="https://user-images.githubusercontent.com/8998518/34523004-d9462a46-f095-11e7-8d3b-97900b58f9fc.png"> Especially the mobile browsers are mandatory targets for our cache since the users will have the least stable connection on those devices. I personally think Mozilla won't outdate the AppCache until the most mobile browsers support ServiceWorkers. So my decision is to keep the AppCache until it is fully supported by Safari (mobile and desktop) and implement ServiceWorkers in sth like v1.3(?).

**Comment by hendriku** [comment]
As we really need this to correctly do v1.1 #86 . I'll also take care of this issue.
