### ISSUE TITLE
Reduce max lines for info at the end 

### ISSUE THREAD

**Issue by hendriku** [dhbw-timetable/rablabla#47]
I think we should support max 2 lines:

<img width="234" alt="bildschirmfoto 2017-11-03 um 12 42 41" src="https://user-images.githubusercontent.com/8998518/32372291-855d2302-c094-11e7-937a-a5a46806971d.png">

**Comment by MalteBartels** [comment]
this should be fixed already. Do you have the newest version from the react branch?

**Comment by hendriku** [comment]
Are you sure you pushed the fix? I tried and there is nothing new...

**Comment by MalteBartels** [comment]
Maximum lines now set to two. Webkit browsers do use ellipsis, none webkit browsers just stop
