### ISSUE TITLE
Weird rectangle beneath messages

### ISSUE THREAD

**Issue by hendriku** [dhbw-timetable/rablabla#49]
![bildschirmfoto 2017-11-04 um 14 44 16](https://user-images.githubusercontent.com/8998518/32405921-cd33aa22-c16e-11e7-913e-d79e27f44b25.png)
![bildschirmfoto 2017-11-04 um 14 44 24](https://user-images.githubusercontent.com/8998518/32405922-cd50b586-c16e-11e7-8f7e-3f3babb32d18.png)

@MalteBartels This only happens to me on extra big displays (WQHD 27").

**Comment by MalteBartels** [comment]
This is correct. I designed it like this.

**Comment by MalteBartels** [comment]
Misunderstanding sorry. No this should NOT be there. I have no idea what this is. Anyway, why is this so huge?

**Comment by MalteBartels** [comment]
Did anybody reproduce this issue, lately? Otherwise the fix worked.

**Comment by hendriku** [comment]
Works fine, thanks @MalteBartels !
