### ISSUE TITLE
NavBar not working on firefox

### ISSUE THREAD

**Issue by lenzenowski** [dhbw-timetable/rablabla#51]
From Firefox:
![image](https://user-images.githubusercontent.com/29572080/32406511-1aeb7302-c17a-11e7-88bc-e2e7fe38df63.png)

@MalteBartels we should fix this before release. Navigation bar displays fine on Win/Chrome but the buttons are not working.

**Comment by lenzenowski** [comment]
@MalteBartels EDIT: Navigation bar is now clickable, was undefined bug. CSS Issues persist.

**Comment by MalteBartels** [comment]
I need more information. Please provide firefox version numbers and operating system.

**Comment by MalteBartels** [comment]
Please provide more information. I need browser version numbers and operating system.

**Comment by hendriku** [comment]
@MalteBartels This also persists on the most recent firefox version (56.0.2) on macOS (High Sierra).

**Comment by hendriku** [comment]
Fixed. Thanks to @MalteBartels!
