### ISSUE TITLE
Messages are not working on WIN

### ISSUE THREAD

**Issue by lenzenowski** [dhbw-timetable/rablabla#52]
1: WIN/Chrome
DELETED
2: WIN/FFOX
![image](https://user-images.githubusercontent.com/29572080/32406595-9e506b48-c17b-11e7-86b9-161cef9e451b.png)

@MalteBartels

**Comment by lenzenowski** [comment]
Point 1 is not actual any longer

new Point: to much space between statements and input field:
![image](https://user-images.githubusercontent.com/29572080/32407041-efdf17aa-c182-11e7-940e-a3575d6b7662.png)

**Comment by MalteBartels** [comment]
@lenzenowski @hendriku What firefox version is this? I need more information, like version numbers and system

**Comment by lenzenowski** [comment]
windows 7, firefox version 52.4.0 (32 bit)

**Comment by hendriku** [comment]
The mentioned unneccesary whitespace is gone for me. @lenzenowski can you confirm, that the scrollbar is also only appearing if many messages are present?

**Comment by hendriku** [comment]
Tested on my windows, works like beautiful charme.
