### ISSUE TITLE
Events not responsive on Win/FFox

### ISSUE THREAD

**Issue by hendriku** [dhbw-timetable/rablabla#61]
Some cut of text informations on small windows (Firefox):
![image](https://user-images.githubusercontent.com/8998518/32465111-a616513a-c342-11e7-9182-50f30f00148e.png)

Less but still some on Chrome:
![image](https://user-images.githubusercontent.com/8998518/32465338-78f35792-c343-11e7-8dd0-5b754f79500b.png)

The hiding of the info and dozent elements is also not done safely. Sometimes the info appears, then the tutor disappears and then the info disappears but the tutor disappears again... Does not seem to be 100% correct. I'd suggest to do it in a cleaner way being aware of hiding informations earlier.

This happens reducing the height every time:
![image](https://user-images.githubusercontent.com/8998518/32465429-b798d29c-c343-11e7-89a4-a881764af39d.png)
![image](https://user-images.githubusercontent.com/8998518/32465448-c57c4312-c343-11e7-83dd-185640e87ac7.png)
![image](https://user-images.githubusercontent.com/8998518/32465462-d61c9960-c343-11e7-94e3-e498a9821a1b.png)

@MalteBartels this is the only thing I've notived within the testing on my windows machine. 

Windows 10
Firefox 56.0 & Chrome

**Comment by MalteBartels** [comment]
@hendriku the latest commits should fix this. Are you still experiencing the issue?

**Comment by hendriku** [comment]
Nope, anything correct now. Thanks!
