### ISSUE TITLE
Fix pinned tab icon for Safari

### ISSUE THREAD

**Issue by MalteBartels** [dhbw-timetable/rablabla#65]
When you pin Rablabla in Safari, it doesn't use the favicon but just the letter 'M' for 'mybluemix'. Someday, there should be the favicon instead.

https://yoast.com/dev-blog/safari-pinned-tab-icon-mask-icon/
Here's how it works.

**Comment by hendriku** [comment]
@MalteBartels is this still active using the staging branch?

**Comment by hendriku** [comment]
Tested and works now for my safari.
