### ISSUE TITLE
Multi week event cache

### ISSUE THREAD

**Issue by MalteBartels** [dhbw-timetable/rablabla#75]
Currently the cached events are displayed all the time, no matter which date you pick. Events should be cached in the future. If there is no data available for the selected week, there should be an error (empty calendar is misleading).

**Comment by hendriku** [comment]
At this time, only the current week is getting cached. And the worst: It is not getting removed automatically. 

According to your suggestion of an error... I think we should do it as the following: If user selects a week, look in the cache if the week is there. If not, simply proceed without notifications. Then start the AJAX request to the server, while this **display a Loading screen/animation e.g. ProgressBar**. This points out, that the data is getting loaded and there may be lessons available. On AJAX success we can simply set the week in the cache and display the correct data. If internet/rapla is not available, display an error message about that.

**Comment by hendriku** [comment]
Oh and we should implement a sync range so that every `localStorage` event data item which is out of the range is getting deleted...

**Comment by hendriku** [comment]
@MalteBartels If you agree to my suggestion, you can create an issue for a loading ProgressBar maybe under the NavBar. Otherwise lets continue discussion.

**Comment by hendriku** [comment]
This will be handeled in #32.
