### ISSUE TITLE
Provide onboarding information via url param

### ISSUE THREAD

**Issue by hendriku** [dhbw-timetable/rablabla#81]
I'd be cool if users who disabled their cache could also take advantage of the design of our app. They could bookmark url params with our url and skip onboarding for this.

This would be a good sample:
`https://rablabla.mybluemix.net/?dhbw=stuttgart&key=oijg4o5ijgo4i5go45bo45imb4oi5go4i5g`

Reason: Firefox clears offline files and so the onboarding would had to be done every time.

**Comment by maximilianbaumann** [comment]
These settings do work and seem to be the maximum of data you can delete on close without beeing forced to reenter the link and course name:
![screenshot](https://user-images.githubusercontent.com/32189482/32833689-edf33e0a-c9ff-11e7-9b40-3b186b137f61.png)

**Comment by hendriku** [comment]
Since providing URL GET parameters via `?a=b` would break our app cache we will implement this with:
`https://rablabla.mybluemix.net/#https://rapla.dhbw-stuttgart.de/rapla?key=1a2b3c4d5e6f7g8h9j&day=9&month=12&year=2016&today=Heute`
