### ISSUE TITLE
Add Arrow Buttons for switching week / month

### ISSUE THREAD

**Issue by maximilianbaumann** [dhbw-timetable/rablabla#82]
It would be nice to have some arrow buttons to switch to the next/previous week in the timetabe.
Similary it would be nice to have some arrow buttons to switch months in the calendar/date-picker modal.

**Comment by hendriku** [comment]
@maximilianbaumann We implemented a new date picker for the v1.1 version. 🎉 It'll present a cleaner interface with the opportunity to choose weeks much easier than before. There'll be arrows for switching the months. I can understand the need of a button to change the current week with one click (without opening date picker) but we are looking forward to more feedback regarding this use case. Keeping this in mind I'll close this issue for v1.1.
